import os
import sys
import importlib.util

mainpath = os.path.dirname(sys.executable if getattr(sys, 'frozen', False) else __file__)


farm_properties = {'Windpark': 'name',
                   'Ort': 'location'}

turbine_properties = {'Hersteller': 'oem',
                      'Modell': 'model',
                      'Untermodell': 'submodel',
                      'Windpark': 'windfarm',
                      'Standort': 'location',
                      'Nennleistung (kW)': 'rated_power',
                      'Nabenhöhe (m)': 'hub_height',
                      'Rotordurchmesser (m)': 'rotor_diam',
                      'Turmtyp': 'tower_type',
                      'Betreiber': 'owner',
                      'Betriebsführer': 'operator',
                      'Seriennummer': 'id',
                      'Parknummer': 'farm_number',
                      'Inbetriebnahmedatum': 'startup_date',
                      'Koordinaten (XX, YY)': 'coordinates',
                      'Kurznotiz': 'note',
                      }

inspection_properties = {'Prüfauftrag': 'kind',
                         'Prüfumfang': 'scope',
                         'Betriebsstunden': 'wea_hours',
                         'Ertrag (kWh)': 'wea_output',
                         'Wind Probelauf': 'testrun_wind',
                         'Leistung Probelauf': 'testrun_power',
                         }

report_properties = {'Nummer': 'id'}

project_properties = {'Name': 'name',
                      'Jahr/ID': 'year_id',
                      'Auftragsdatum': 'order_date',
                      'Ansprechpartner': 'contact',
                      'Auftragnehmer': 'contractor',
                      'Unterauftragnehmer': 'subcontractor',
                      'Verantwortl. Ingenieur' : 'engineer',
                      }

standalone_chapter_str = '-'
db_split_char = '|'

inspection_type_translator = {
    'IB': 'Technische Überprüfung einer Windenergieanlage nach Inbetriebnahme',
    'GAP': 'Technische Überprüfung einer Windenergieanlage vor Ablauf der Gewährleistung',
    'WKP': 'Wiederkehrende Prüfung einer Windenergieanlage',
    'ZOP': 'Zustandorientierte Prüfung|Der Prüfumfang einer wiederkehrenden Prüfung wird mit abgedeckt',
}


def load_config():
    base_dir = os.path.dirname(sys.executable if getattr(sys, 'frozen', False) else __file__)
    config_path = os.path.join(base_dir, "config.py")

    if not os.path.exists(config_path):
        print("config.py not found!\ncreating config.py from template.")
        with open(config_path, 'w') as f:
            f.write(get_default_config())

    spec = importlib.util.spec_from_file_location("config", config_path)
    config = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(config)
    return config

def get_default_config():
    return '''
default_contractor = ('8.2 Ingenieurbüro Deine Firma|'
                      'Deine-Str. 123|'
                      '12345 Deine Stadt|'
                      'Telefon: 0112 / 358 1321|'
                      'Mail:    dein.name@8p2.de')
default_engineer = 'Dipl.-Ing. Dein Name'
default_inspectors = [('Prüfung', 'Dein Name, 8.2', '', ''),
                      ('Begleitung', 'Dein Kumpane, 8.2', '', '')]
default_author = 'Dein Name'
footnote_companyname = '8.2 Ingenieurbüro Deine Firma'
footnote_companyname_abbrev = '8.2 Ing.-Büro DF'
default_images = ['8p2_logo'] # images that are needed in the report, must be located in databases/report/
projects_path = 'C:/Users/deinname/Pfad/Zu/Deinen/Projekten'
default_image_width_pxl = 500
default_done_chapters = ['Allgemeine Daten|Prüfbericht|Zugehörige Dokumente',
                         'Allgemeine Daten|Prüfbericht|Änderungen in dieser Revision',
                         'Allgemeine Daten|Legende zum Prüfbericht|Im Fazit verwendete Farben',
                         'Prüfungsgrundlagen|Prüfungsgrundlage',
                         'Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Pflichten des Auftraggebers bzw. des Betreibers']
'''


def get_default_checklist_dict():
    return {
            'index': [
                ('Allgemeine Daten|Prüfbericht|Zugehörige Dokumente', 'Introsatz', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Eiserkennung', 1),
                ('Prüfbemerkungen|Außenbereich', 'Kranstellfläche belegt', 1),
                ('Prüfbemerkungen|Betriebsverhalten und Sicherheitssysteme', 'Abschalt-Windgeschwindigkeit', 1),
                ('Prüfbemerkungen|Dokumentation', 'Bedienungsanleitung i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Betonteil', 'Abplatzungen', 1),
                ('Prüfbemerkungen|Fundament und Turm|Fundament', 'Dichtung nicht i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Kabel / Elektrische Komponenten', 'Aufhängung auffällig', 1),
                ('Prüfbemerkungen|Fundament und Turm|Korrosion / Beschichtung', 'Beschichtungsdicke gering', 1),
                ('Prüfbemerkungen|Fundament und Turm|Kühlung der elektrischen Einrichtungen', 'Schlauch auffällig', 1),
                ('Prüfbemerkungen|Fundament und Turm|Luftführung / Kühlung der elektrischen Einrichtungen', 'Nebenteil auffällig', 1),
                ('Prüfbemerkungen|Fundament und Turm|Plattformen / Einbauteile', 'Absturzgefahr', 1),
                ('Prüfbemerkungen|Fundament und Turm|Schaltschränke', 'Brandlast', 1),
                ('Prüfbemerkungen|Fundament und Turm|Schrauben und Flansche', 'Flansch feucht', 1),
                ('Prüfbemerkungen|Fundament und Turm|Schweißnähte und Blechoberflächen', 'Korrosion Schweißnaht', 1),
                ('Prüfbemerkungen|Fundament und Turm|Sektionsstöße und Verbindungsplatten', 'Dichtung fehlerhaft', 1),
                ('Prüfbemerkungen|Fundament und Turm|Turm außen', 'Beschichtungsschäden Schweißnaht', 1),
                ('Prüfbemerkungen|Fundament und Turm|Tür und Eingangsbereich', 'Anbauteile Tür auffällig', 1),
                ('Prüfbemerkungen|Fundament und Turm|Übergangsstück Beton-Stahl', 'Korrosion', 1),
                ('Prüfbemerkungen|Generator', 'Anschlusskabel i.O.', 1),
                ('Prüfbemerkungen|Instandhaltung', 'Arbeiten nachvollziehbar dokumentiert', 1),
                ('Prüfbemerkungen|Kennzeichnung', 'Erste Hilfe Schild i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Azimutlagerung / Windnachführung', 'Antriebe ansonsten i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Dachaufbauten', 'Funktion auffällig', 1),
                ('Prüfbemerkungen|Maschinenhaus|Hydraulik', 'Leckage', 1),
                ('Prüfbemerkungen|Maschinenhaus|Hydraulik (Rotorarretierung)', 'Korrosion', 1),
                ('Prüfbemerkungen|Maschinenhaus|Kabel / Beleuchtung / Einbauteile', 'Kabel beschädigt', 1),
                ('Prüfbemerkungen|Maschinenhaus|Lastenwinde', 'Nebenteil beschädigt', 1),
                ('Prüfbemerkungen|Maschinenhaus|Lüfter / Luftführung Maschine', 'Geräusche', 1),
                ('Prüfbemerkungen|Maschinenhaus|Maschinenhausverkleidung', 'Befestigung auffällig', 1),
                ('Prüfbemerkungen|Maschinenhaus|Maschinenträger und tragende Elemtente', 'Fehlstelle', 1),
                ('Prüfbemerkungen|Maschinenhaus|Podeste / Einbauteile / Hinweisschilder', 'Abdeckung auffällig', 1),
                ('Prüfbemerkungen|Maschinenhaus|Rotorarretierung', 'alles i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Rotorbremse', 'Funktion auffällig', 1),
                ('Prüfbemerkungen|Maschinenhaus|Schaltschränke in der Gondel', 'Abdichtung nicht i.O.', 1),
                ('Prüfbemerkungen|Netzanbindung', 'Ort Trafo + MS-SA', 1),
                ('Prüfbemerkungen|Netzanbindung|Schaltanlage', 'Beschriftung nicht i.O.', 1),
                ('Prüfbemerkungen|Netzanbindung|Sonstiges', 'Schmauchspuren', 1),
                ('Prüfbemerkungen|Netzanbindung|Trafo', 'Anschlüsse auffällig', 1),
                ('Prüfbemerkungen|Netzanbindung|Zugang / Kennzeichnung / Bedienung', 'Kennzeichnung auffällig', 1),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz', 'Abseilgerät i.O.', 1),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz|Leiter und Steigschutz', 'Abrieb', 1),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz|Servicelift', 'Nebenteil auffällig', 1),
                ('Prüfbemerkungen|Rotorsystem|Blitzableiteinrichtungen', 'Funkenstrecke lang', 1),
                ('Prüfbemerkungen|Rotorsystem|Nabe', 'Beschichtungsschäden außen', 1),
                ('Prüfbemerkungen|Rotorsystem|Pitchsystem', 'Antrieb ansonsten i.O.', 1),
                ('Prüfbemerkungen|Rotorsystem|Rotorblätter', 'Aluring auffällig', 1),
                ('Prüfbemerkungen|Rotorsystem|Sonstiges', 'Mängel Tiphydraulik', 1),
                ('Prüfbemerkungen|Rotorsystem|Spinner', 'Befestigung auffällig', 1),
                ('Prüfbemerkungen|Rotorsystem|Steuerschränke', 'Gehäuse auffällig', 1),
                ('Prüfbemerkungen|Rotorsystem|Tiphydraulik', 'Leckage', 1),
                ('Prüfbemerkungen|Rotorsystem|Verschraubungen', 'Fettaustritt', 1),
                ('Prüfbemerkungen|Triebstrang|Bremse', 'Belagstärke gering', 1),
                ('Prüfbemerkungen|Triebstrang|Drehdurchführung', 'Leckage', 1),
                ('Prüfbemerkungen|Triebstrang|Getriebe', 'Korrosion', 1),
                ('Prüfbemerkungen|Triebstrang|Getriebeöl/Schmierung', 'Leckage', 1),
                ('Prüfbemerkungen|Triebstrang|Hauptlager und Hauptwelle', 'Blitzableitung auffällig', 1),
                ('Prüfbemerkungen|Triebstrang|Kupplung', 'alles i.O.', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'Intro kurzfristig', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Pflichten des Auftraggebers bzw. des Betreibers', 'Nachweise einholen', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise', 'Fettaustritt Blattbolzen', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Termin für die wiederkehrende Prüfung', 'Prüfumfang WKP', 1),
                ('Prüfergebnis|Fazit', 'ANTRIEBSSTRANG', 1),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'Flugbefeuerung', 1),
                ('Prüfungsgrundlagen|Prüfliste', 'Info Datenauslese', 1),
                ('Prüfungsgrundlagen|Prüfungsgrundlage', 'DIBt Richtlinie', 1),
                ('Allgemeine Daten|Prüfbericht|Zugehörige Dokumente', 'Prüfbericht Rotorblätter', 1),
                ('Allgemeine Daten|Prüfbericht|Zugehörige Dokumente', 'Prüfbericht Rotorblätter', 2),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Tageskennzeichnung', 5),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'keine', 1),
                ('Prüfbemerkungen|Außenbereich', 'Zugang i.O.', 1),
                ('Prüfbemerkungen|Außenbereich', 'Zugang nicht i.O.', 1),
                ('Prüfbemerkungen|Betriebsverhalten und Sicherheitssysteme', 'kein Probelauf', 3),
                ('Prüfbemerkungen|Betriebsverhalten und Sicherheitssysteme', 'kein Probelauf', 4),
                ('Prüfbemerkungen|Dokumentation', 'nur Doku in Anlage betrachtet', 1),
                ('Prüfbemerkungen|Dokumentation', 'nur Doku in Anlage betrachtet', 2),
                ('Prüfbemerkungen|Fundament und Turm|Betonteil', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Betonteil', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Fundament und Turm|Fundament', 'Wasser auf Fundament', 2),
                ('Prüfbemerkungen|Fundament und Turm|Fundament', 'Wasser auf Fundament', 3),
                ('Prüfbemerkungen|Fundament und Turm|Kabel / Elektrische Komponenten', 'ansonsten i.O.', 3),
                ('Prüfbemerkungen|Fundament und Turm|Kabel / Elektrische Komponenten', 'mangelhafte Kennzeichnung', 1),
                ('Prüfbemerkungen|Fundament und Turm|Korrosion / Beschichtung', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Korrosion / Beschichtung', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Fundament und Turm|Kühlung der elektrischen Einrichtungen', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Luftführung / Kühlung der elektrischen Einrichtungen', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Luftführung / Kühlung der elektrischen Einrichtungen', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Fundament und Turm|Plattformen / Einbauteile', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Plattformen / Einbauteile', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Fundament und Turm|Schaltschränke', 'defekte Teile', 1),
                ('Prüfbemerkungen|Fundament und Turm|Schaltschränke', 'defekte Teile', 2),
                ('Prüfbemerkungen|Fundament und Turm|Schrauben und Flansche', 'ungewöhnlicher Klang', 1),
                ('Prüfbemerkungen|Fundament und Turm|Schrauben und Flansche', 'ungewöhnlicher Klang', 2),
                ('Prüfbemerkungen|Fundament und Turm|Schweißnähte und Blechoberflächen', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Fundament und Turm|Schweißnähte und Blechoberflächen', 'unverschlossene Löcher', 1),
                ('Prüfbemerkungen|Fundament und Turm|Sektionsstöße und Verbindungsplatten', 'alles i.O.', 2),
                ('Prüfbemerkungen|Fundament und Turm|Sektionsstöße und Verbindungsplatten', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Turm außen', 'provisorischer Stand', 1),
                ('Prüfbemerkungen|Fundament und Turm|Turm außen', 'unbefestigte Teile', 1),
                ('Prüfbemerkungen|Fundament und Turm|Tür und Eingangsbereich', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Tür und Eingangsbereich', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Fundament und Turm|Übergangsstück Beton-Stahl', 'alles i.O.', 1),
                ('Prüfbemerkungen|Fundament und Turm|Übergangsstück Beton-Stahl', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Generator', 'alles i.O.', 1),
                ('Prüfbemerkungen|Generator', 'lose Teile', 1),
                ('Prüfbemerkungen|Instandhaltung', 'kein Überdrehzahltest', 1),
                ('Prüfbemerkungen|Instandhaltung', 'keine Wartungen', 1),
                ('Prüfbemerkungen|Kennzeichnung', 'äußerliche Mängel Kennzeichnung', 1),
                ('Prüfbemerkungen|Kennzeichnung', 'äußerliche Mängel Kennzeichnung', 2),
                ('Prüfbemerkungen|Maschinenhaus|Azimutlagerung / Windnachführung', 'Tragbild i.O.', 2),
                ('Prüfbemerkungen|Maschinenhaus|Azimutlagerung / Windnachführung', 'Tragbild i.O.', 3),
                ('Prüfbemerkungen|Maschinenhaus|Dachaufbauten', 'alles i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Dachaufbauten', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Hydraulik', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Maschinenhaus|Hydraulik', 'ansonsten i.O.', 3),
                ('Prüfbemerkungen|Maschinenhaus|Hydraulik (Rotorarretierung)', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Hydraulik (Rotorarretierung)', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Maschinenhaus|Kabel / Beleuchtung / Einbauteile', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Maschinenhaus|Kabel / Beleuchtung / Einbauteile', 'ansonsten i.O.', 3),
                ('Prüfbemerkungen|Maschinenhaus|Lastenwinde', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Lastenwinde', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Maschinenhaus|Lüfter / Luftführung Maschine', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Maschinenhaus|Lüfter / Luftführung Maschine', 'ansonsten i.O.', 3),
                ('Prüfbemerkungen|Maschinenhaus|Maschinenhausverkleidung', 'ansonsten i.O.', 3),
                ('Prüfbemerkungen|Maschinenhaus|Maschinenhausverkleidung', 'falsche Dämpfer', 1),
                ('Prüfbemerkungen|Maschinenhaus|Maschinenträger und tragende Elemtente', 'ansonsten i.O.', 5),
                ('Prüfbemerkungen|Maschinenhaus|Maschinenträger und tragende Elemtente', 'ansonsten i.O.', 6),
                ('Prüfbemerkungen|Maschinenhaus|Podeste / Einbauteile / Hinweisschilder', 'unverbautes Material', 1),
                ('Prüfbemerkungen|Maschinenhaus|Podeste / Einbauteile / Hinweisschilder', 'unverbautes Material', 2),
                ('Prüfbemerkungen|Maschinenhaus|Rotorarretierung', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Maschinenhaus|Rotorbremse', 'Öl auf Bremsscheibe', 2),
                ('Prüfbemerkungen|Maschinenhaus|Rotorbremse', 'Öl auf Bremsscheibe', 3),
                ('Prüfbemerkungen|Maschinenhaus|Schaltschränke in der Gondel', 'ansonsten i.O.', 3),
                ('Prüfbemerkungen|Maschinenhaus|Schaltschränke in der Gondel', 'ungeöffneter Schrank', 1),
                ('Prüfbemerkungen|Netzanbindung', 'Ort Trafo + MS-SA', 5),
                ('Prüfbemerkungen|Netzanbindung', 'nicht geprüft', 1),
                ('Prüfbemerkungen|Netzanbindung|Schaltanlage', 'ansonsten i.O.', 4),
                ('Prüfbemerkungen|Netzanbindung|Schaltanlage', 'keine Spannungsanzeiger', 1),
                ('Prüfbemerkungen|Netzanbindung|Sonstiges', 'Station auffällig', 1),
                ('Prüfbemerkungen|Netzanbindung|Sonstiges', 'Station auffällig', 2),
                ('Prüfbemerkungen|Netzanbindung|Trafo', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Netzanbindung|Trafo', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Netzanbindung|Zugang / Kennzeichnung / Bedienung', 'Tür auffällig', 1),
                ('Prüfbemerkungen|Netzanbindung|Zugang / Kennzeichnung / Bedienung', 'alles i.O.', 1),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz', 'PSA nicht i.O.', 5),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz', 'PSA nicht i.O.', 6),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz|Leiter und Steigschutz', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz|Servicelift', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz|Servicelift', 'kein Notfallplan', 1),
                ('Prüfbemerkungen|Rotorsystem|Blitzableiteinrichtungen', 'alles i.O.', 2),
                ('Prüfbemerkungen|Rotorsystem|Blitzableiteinrichtungen', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Rotorsystem|Nabe', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Rotorsystem|Nabe', 'nicht prüfbar', 1),
                ('Prüfbemerkungen|Rotorsystem|Pitchsystem', 'Zentralschmieranlage auffällig', 1),
                ('Prüfbemerkungen|Rotorsystem|Pitchsystem', 'Zentralschmieranlage auffällig', 2),
                ('Prüfbemerkungen|Rotorsystem|Rotorblätter', 'ohne Seil i.O.', 1),
                ('Prüfbemerkungen|Rotorsystem|Rotorblätter', 'ohne Seil i.O.', 2),
                ('Prüfbemerkungen|Rotorsystem|Sonstiges', 'Tiphydraulik ansonsten i.O.', 1),
                ('Prüfbemerkungen|Rotorsystem|Spinner', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Rotorsystem|Spinner', 'kein Spinner', 1),
                ('Prüfbemerkungen|Rotorsystem|Steuerschränke', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Rotorsystem|Steuerschränke', 'ansonsten i.O.', 3),
                ('Prüfbemerkungen|Rotorsystem|Tiphydraulik', 'alles i.O.', 1),
                ('Prüfbemerkungen|Rotorsystem|Tiphydraulik', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Rotorsystem|Verschraubungen', 'Wassereintritt', 1),
                ('Prüfbemerkungen|Rotorsystem|Verschraubungen', 'falscher Einbau', 1),
                ('Prüfbemerkungen|Triebstrang|Bremse', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Triebstrang|Bremse', 'nicht prüfbar', 1),
                ('Prüfbemerkungen|Triebstrang|Drehdurchführung', 'ansonsten i.O.', 2),
                ('Prüfbemerkungen|Triebstrang|Drehdurchführung', 'nicht einsehbar', 1),
                ('Prüfbemerkungen|Triebstrang|Getriebe', 'elastische Bauteile beschädigt', 1),
                ('Prüfbemerkungen|Triebstrang|Getriebe', 'schnelle Stufe i.O.', 1),
                ('Prüfbemerkungen|Triebstrang|Getriebeöl/Schmierung', 'Ölstand nicht i.O.', 1),
                ('Prüfbemerkungen|Triebstrang|Getriebeöl/Schmierung', 'Ölstand nicht i.O.', 2),
                ('Prüfbemerkungen|Triebstrang|Hauptlager und Hauptwelle', 'alles i.O.', 3),
                ('Prüfbemerkungen|Triebstrang|Hauptlager und Hauptwelle', 'ansonsten i.O.', 1),
                ('Prüfbemerkungen|Triebstrang|Kupplung', 'nicht einsehbar', 1),
                ('Prüfbemerkungen|Triebstrang|Kupplung', 'ungenutzte Schmieranschlüsse', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'ungenannte Mängel letzte Prüfung wurden beseitigt', 3),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'vor Wiederinbetriebnahme erledigen', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Pflichten des Auftraggebers bzw. des Betreibers', 'Verantwortung langjähriger Betrieb', 2),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Pflichten des Auftraggebers bzw. des Betreibers', 'Zuweisung Verantwortlichkeiten', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise', 'Stellungnahme Intro', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise', 'Temperatur', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Termin für die wiederkehrende Prüfung', 'Termin WKP', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Termin für die wiederkehrende Prüfung', 'Termin WKP', 2),
                ('Prüfergebnis|Fazit', 'WEITERER BETRIEB', 1),
                ('Prüfergebnis|Fazit', 'kein Probelauf', 1),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'kein Probelauf', 3),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'kein Probelauf', 4),
                ('Prüfungsgrundlagen|Prüfliste', 'Standard Prüfliste', 1),
                ('Prüfungsgrundlagen|Prüfliste', 'alte Berichte', 1),
                ('Prüfungsgrundlagen|Prüfungsgrundlage', 'Regeln der Technik', 1),
                ('Prüfungsgrundlagen|Prüfungsgrundlage', 'Richtlinien WEA', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Fledermausabschaltung', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Flight Manager', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Monitoringsystem', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Nachtkennzeichnung', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Nachtkennzeichnung', 2),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Niederschlagssensor', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'RBL Extras', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Schalloptimierung', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Schattenabschaltung', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Sichtweitenmessgerät', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Tageskennzeichnung', 1),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Tageskennzeichnung', 2),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Tageskennzeichnung', 3),
                ('Anlagendaten|Zusätzliche Ausrüstung der Anlage', 'Tageskennzeichnung', 4),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'Intro umgehend', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'Intro vor Wiederinbetriebnahme', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'Zeitpunkt Rest', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'Zeitpunkt Rest', 2),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'kurzfristig erledigen', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'kurzfristig erledigen', 2),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'kurzfristig erledigen', 3),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'umgehend erledigen', 2),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'ungenannte Mängel letzte Prüfung wurden beseitigt', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung', 'ungenannte Mängel letzte Prüfung wurden beseitigt', 2),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Pflichten des Auftraggebers bzw. des Betreibers', 'Verantwortung langjähriger Betrieb', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise', 'Fettaustritt Hauptwelle/Hauptlager', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise', 'Risse Fundament', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise', 'Risse Fundament', 2),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise', 'Schweißnaht', 1),
                ('Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Termin für die wiederkehrende Prüfung', 'Prüfumfang WKP', 2),
                ('Prüfergebnis|Fazit', 'ARBEITSSICHERHEIT', 1),
                ('Prüfergebnis|Fazit', 'BETRIEBSCHARAKTERISTIK', 1),
                ('Prüfergebnis|Fazit', 'Detail Antriebsstrang', 1),
                ('Prüfergebnis|Fazit', 'Detail Arbeitssicherheit', 1),
                ('Prüfergebnis|Fazit', 'Detail Betrieb', 1),
                ('Prüfergebnis|Fazit', 'Detail Betrieb', 2),
                ('Prüfergebnis|Fazit', 'Detail Instandhaltung', 1),
                ('Prüfergebnis|Fazit', 'Detail Instandhaltung', 2),
                ('Prüfergebnis|Fazit', 'Detail Sicherheitssysteme', 1),
                ('Prüfergebnis|Fazit', 'Detail Sonstiges', 1),
                ('Prüfergebnis|Fazit', 'Detail Sonstiges', 2),
                ('Prüfergebnis|Fazit', 'Detail Sonstiges', 3),
                ('Prüfergebnis|Fazit', 'Detail Standsicherheit', 1),
                ('Prüfergebnis|Fazit', 'Detail Weiterer Betrieb', 1),
                ('Prüfergebnis|Fazit', 'Fazit Antriebsstrang', 1),
                ('Prüfergebnis|Fazit', 'Fazit Antriebsstrang', 2),
                ('Prüfergebnis|Fazit', 'Fazit Antriebsstrang', 3),
                ('Prüfergebnis|Fazit', 'Fazit Arbeitssicherheit', 1),
                ('Prüfergebnis|Fazit', 'Fazit Arbeitssicherheit', 2),
                ('Prüfergebnis|Fazit', 'Fazit Betriebscharakteristik', 1),
                ('Prüfergebnis|Fazit', 'Fazit Betriebscharakteristik', 2),
                ('Prüfergebnis|Fazit', 'Fazit Instandhaltung', 1),
                ('Prüfergebnis|Fazit', 'Fazit Instandhaltung', 2),
                ('Prüfergebnis|Fazit', 'Fazit Instandhaltung', 3),
                ('Prüfergebnis|Fazit', 'Fazit Sicherheitssysteme', 1),
                ('Prüfergebnis|Fazit', 'Fazit Sicherheitssysteme', 2),
                ('Prüfergebnis|Fazit', 'Fazit Standsicherheit', 1),
                ('Prüfergebnis|Fazit', 'Fazit Standsicherheit', 2),
                ('Prüfergebnis|Fazit', 'Fazit Standsicherheit', 3),
                ('Prüfergebnis|Fazit', 'Fazit Weiterer Betrieb', 1),
                ('Prüfergebnis|Fazit', 'Fazit Weiterer Betrieb', 2),
                ('Prüfergebnis|Fazit', 'GESAMTEINDRUCK', 1),
                ('Prüfergebnis|Fazit', 'Gesamteindruck', 1),
                ('Prüfergebnis|Fazit', 'Gesamteindruck', 2),
                ('Prüfergebnis|Fazit', 'Gesamteindruck', 3),
                ('Prüfergebnis|Fazit', 'Hauptmängel', 1),
                ('Prüfergebnis|Fazit', 'Hauptmängel', 2),
                ('Prüfergebnis|Fazit', 'INSTANDHALTUNG', 1),
                ('Prüfergebnis|Fazit', 'Menge Mängel', 1),
                ('Prüfergebnis|Fazit', 'Menge Mängel', 2),
                ('Prüfergebnis|Fazit', 'Menge Mängel', 3),
                ('Prüfergebnis|Fazit', 'Menge Mängel', 4),
                ('Prüfergebnis|Fazit', 'SICHERHEITSSYSTEME', 1),
                ('Prüfergebnis|Fazit', 'SONSTIGES', 1),
                ('Prüfergebnis|Fazit', 'STANDSICHERHEIT', 1),
                ('Prüfergebnis|Fazit', 'Stilllegung', 1),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'Traforaum', 1),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'Traforaum', 2),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'Traforaum', 3),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'kein Probelauf', 1),
                ('Prüfungsgrundlagen|Nicht durchgeführte Prüfungen', 'kein Probelauf', 2),
                ('Prüfungsgrundlagen|Prüfliste', 'Intro', 1),
                ('Prüfungsgrundlagen|Prüfliste', 'Probelauf', 1),
                ('Prüfungsgrundlagen|Prüfliste', 'Probelauf', 2),
                ('Prüfungsgrundlagen|Prüfliste', 'Probelauf', 3),
                ('Prüfungsgrundlagen|Prüfliste', 'Probelauf', 4),
                ('Prüfungsgrundlagen|Prüfliste', 'RBLi', 1)],
            'columns': [
                'fulltext', 'blacklist', 'whitelist', 'default_state', 'recommended_flag', 'bg_color', 'author'],
            'data': [
                ['Zu diesem Prüfbericht gehören folgende Dokumente:', '', '', '', 'S', '', 'Tade Jensen'],
                ['Eissensorik an den Rotorblättern', '', '', '', '-', '', 'Tade Jensen'],
                ['Die Kranstellfläche ist nicht vollständig nutzbar, da sie durch einen Erdhaufen belegt ist.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Die Abschalt-Windgeschwindigkeit ist auf 25 m/s im 10 Min.-Mittel eingestellt.', '', 'Senvion', '', 'V', '', ''],
                ['Eine Bedienungsanleitung ist vorhanden.', '', '', '', 'V', 'green', ''],
                ['Am Betonring oberhalb der Lifteinstiegsplattform platzt offenbar ein kleines Stück Beton ab. Abhilfe ist erforderlich, damit keine Gefahr durch das herabfallende Bruchstück entsteht und die vorgesehene Betonüberdeckung der Bewehrung wieder hergestellt wird.', '', 'Beton,', '', 'P', '', 'Tade Jensen'],
                ['Die Dichtung zwischen Fundamentkörper und Einbauteil liegt stellenweise nicht an, sodass Wasser eintreten kann. Die Dichtung muss instand gesetzt werden.', '', 'Enercon,', '', 'P', '', 'Tade Jensen'],
                ['Oben im Turm sind einige Kabel durch Führungen geführt, in denen sie schwingen können. Die Kabel sollten fixiert werden, damit sie sich die Mäntel nicht mit der Zeit an der Führung abscheuern.', '', '', '', 'E', '', ''],
                ['Die Beschichtungsdicke reicht in der Sektion XXX nicht aus.', '', '', '', 'p', '', ''],
                ['Das Lüftungsrohr des Trafos liegt nach wie vor an der Kante des Türrahmens an. Hier ist ein Schutz erforderlich.', '', 'Senvion,', '', '', '', 'Tade Jensen'],
                ['Die Beschichtung der Lufthutzen oben im Betonteil ist beschädigt und muss nachgebessert werden.', '', 'Enercon,', '', '', '', 'Tade Jensen'],
                ['In der Plattform am Stoß zwischen den untersten beiden Stahlblechsektionen sind größere Öffnungen vorhanden. Die Öffnungen sollten abgedeckt werden, um den Arbeitsschutz zu verbessern.', '', '', '', 'E', '', 'Tade Jensen'],
                ['Im Nebenschrank befindet sich am Boden etwas Öl, das wegen der zusätzlichen Brandlast entfernt werden sollte.', '', '', '', '', '', ''],
                ['Auf dem Flansch zwischen den Sektionen 2/3 befindet sich Wasser. Zum Ursprung des Wassers siehe Bemerkungen und .', '', 'Stahlrohr,', '', '', '', ''],
                ['An diversen Schweißnähten sind Beschichtungsschäden z.T. mit Korrosion vorhanden. Teilweise wurden die Stellen nachgebessert. Diese Arbeiten wurden jedoch nicht fachgerecht ausgeführt, Korrosion schlägt wieder durch. Fachgerechte Nacharbeit (Korrosion entfernen, reinigen, grundieren, beschichten) ist erforderlich.\r\nBetroffen ist der Türrahmen.', '', '', '', '', '', ''],
                ['Zwischen den Sektionen 1 und 2 scheint an zwei Stellen Licht durch die Turmdichtung. Hier dringt Wasser in den Turm. Die Stellen wurden im Zuge der Prüfung markiert. Eine Abdichtung von außen ist erforderlich.', '', 'Stahlblech,', '', '', '', ''],
                ['Unten am Turm sind an einigen Schweißnähten (Türrahmen, Halterung Eingangspodest) Beschichtungsschäden vorhanden, Korrosion ist noch nicht entstanden. Die Beschichtung muss fachgerecht ausgebessert werden, bevor es zu Korrosion kommt.', 'Beton,', '', '', '', '', 'Tade Jensen'],
                ['Am Filtergitter der Tür fehlt eine Mutter.', '', '', '', '', '', ''],
                ['Auf dem Übergangsstück befinden sich augenscheinlich rostige Partikel, die entfernt werden müssen, um einer Ausweitung der Korrosion vorzubeugen.', '', 'Beton,', '', '', '', 'Tade Jensen'],
                ['Die Anschlusskabel sind fachgerecht verlegt und scheuern nirgends.', '', '', '', 'V', '', ''],
                ['Die Instandhaltungsmaßnahmen (Wartung, Inspektion, Instandsetzung, Verbesserung) sind nachvollziehbar dokumentiert.', '', '', '', 'V', '', ''],
                ['Ein Schild zur ersten Hilfe ist vorhanden und ausgefüllt.', '', '', '', 'V', 'green', ''],
                ['Die Azimutantriebe zeigen ansonsten keine augenscheinlichen Mängel, die Ölstände sind in Ordnung.', '', '', '', 'I', 'yellow', ''],
                ['Die Nachkennzeichnung ist auch tagsüber aktiv. Eine Instandsetzung ist erforderlich.', '', '', '', 'P', '', 'Tade Jensen'],
                ['In der Auffangwanne der Hydraulikstation befindet sich offenbar Öl, eine aktuelle Leckage ist nicht feststellbar. Das Öl sollte entfernt werden, um einer (weiteren) Verschmutzung der darunter liegenden Bereiche vorzubeugen.', 'Enercon,', '', '', '', '', ''],
                ['Am Träger des Arretierbolzens auf 9 Uhr ist Korrosion vorhanden, die beseitigt werden muss.', '', 'Enercon,', '', '', 'green', ''],
                ['Es sind nach wie vor Schäden an einem Kabelmantel an der Einführung in den Generator-Anschlusskasten vorhanden. Die beschädigte Stelle sollte mit einer Muffe o.Ä. repariert werden.', '', '', '', '', '', 'Tade Jensen'],
                ['Der Schutzkegel ist nach wie vor beschädigt.', '', '', '', '', '', ''],
                ['Der Hecklüfter quietscht im Freilauf ein Mal pro Umdrehung. Die Schmierung der Lager sollte verbessert werden.', '', '', '', '', '', 'Tade Jensen'],
                ['Die Nietmuttern vorn am Boden der Verkleidung sind nach wie vor stark korrodiert und werden versagen. Ein Austausch gegen eine dauerhafte Ausführung ist erforderlich, der Korrosionsschutz durch Wachs ist keine dauerhafte Lösung.', '', 'Vestas,', '', 'P', '', 'Tade Jensen'],
                ['Rechts neben der Hauptwelle befindet sich eine Fehlstelle von ca. 8x20\\,cm und einer Tiefe von ca. 1\\,cm im Maschinenträger.\\todo{Stellungnahme fordern? Ich würde es wegen des Alters der Anlage als reine Info belassen.}', '', '', '', '', '', ''],
                ['An der Abdeckung der Kupplung lässt sich hinten links eine Schraube nicht herausdrehen. Eine Reparatur ist erforderlich.', '', '', '', '', '', ''],
                ['Die Rotorarretierung arbeitet einwandfrei, keine augenscheinlichen Mängel.', 'Enercon,', '', '', 'V', '', ''],
                ['Die Rotorbremse schließt nicht selbsttätig. Bei Betätigung des Bremsschalters bzw. Notstopps arbeitet zwar die Hydraulikpumpe, allerdings ohne Effekt. Offenbar kommt es zum hydraulischen Kurzschluss. Zum Betätigen der Rotorbremse muss manuell der Hebel QM6 an der Hydraulikstation betätigt werden, daher lässt sich die Maschine nur vom Maschinenhaus aus stillsetzen. Eine Instandsetzung ist erforderlich.\r\nNach der Prüfung wurde Enercon über diesen Umstand informiert.', '', 'Enercon,', '', '', '', 'Tade Jensen'],
                ['An dem Schrank der Flugbefeuerung sind ungenutzte PG-Verschraubungen nicht verschlossen. Es ist unklar, ob die erforderliche Schutzklasse unter diesen Umständen erreicht wird.', '', '', '', '', '', ''],
                ['Der Trafo und die Mittelspannungsschaltanlage befinden sich im Turmkeller.', '', '', '', 'I', '', ''],
                ['Die Schaltanlage ist nicht beschriftet.', '', '', '', 'P', '', ''],
                ['Oberhalb des Trafos befinden sich Schmauchspuren an der Unterseite der Eingangsplattform.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Ein Niederspannnungsanschluss ist dunkel verfärbt. Die Ursache dürfte eine Überhitzung aufgrund eines erhöhten Übergangswiderstandes sein. Der Anschluss muss überprüft werden, ggf. ist Nacharbeit erforderlich.', '', '', '', 'P', '', 'Tade Jensen'],
                ["Das Hinweisschild ``Hochspannung Lebensgefahr'' ist nach wie vor verblasst und sollte erneuert werden.", '', '', '', 'E', '', ''],
                ['Ein Abseilgerät mit gültiger Prüfung ist im Maschinenhaus vorhanden.', '', '', '', 'V', '', ''],
                ['An den Leiterhaltern auf dem Fundament ist etwas Abrieb entstanden, Abhilfe ist erforderlich.', '', 'Vestas,', '', 'P', '', ''],
                ['Der Kasten der Not-Bedienstelle des Lifts war zum Zeitpunkt der Prüfung geöffnet, eine Ursache für einen Notablass war nicht erkennbar.', '', '', '', '', '', 'Tade Jensen'],
                ['Die Funkenstrecke am Übergang zwischen Rotor und Maschinenhaus des Blitzableiters von Blatt B beträgt 2\\,cm. Es muss anhand der Zeichnungen geprüft werden, ob dies innerhalb der Vorgaben liegt. Ggf. ist eine Justierung erforderlich.', '', '', '', 'P', '', 'Tade Jensen'],
                ['Außen an der Nabe sind diverse kleine Beschichtungsschäden mit Korrosion zu erkennen, die fachgerecht ausgebessert werden müssen.', '', '', '', '', '', ''],
                ['An den Pitchantrieben sind ansonsten keine nennenswerten Mängel feststellbar.', 'Vestas,', '', '', 'I', 'yellow', ''],
                ['In der Blattwurzel von Blatt 3 sind nach wie vor Auffälligkeiten vorhanden. Augenscheinlich handelt es sich hierbei im Kratzer, Anzeichen von Rissen sind nicht erkennbar.', '', 'Vestas V47 - 660 kW,', '', '', '', ''],
                ['Am der Deckel des Anschlusskastens der Tiphydraulik fehlen nach wie vor zwei der vier Befestigungsschrauben. Weiterhin ist der Tank stark verrostet und sollte besser gegen Korrosion geschützt werden. Abhilfe ist erforderlich.', '', 'Nortank AF 1987 A/S,', '', '', '', ''],
                ['An einer Schraube des vorderen Deckels am Spinner fehlt eine Mutter, sie muss angebracht werden.', '', '', '', 'P', '', 'Tade Jensen'],
                ['Am Kondensatorschrank von Blatt B befindet sich ein nicht abgedeckter ungenutzter Stecker. Zum Schutz vor Schmutz und Feuchtigkeit sollte eine Abdeckung angebracht werden.', '', '', '', '', '', ''],
                ['Der Bereich der Tips aller Blätter ist offenbar durch Hydrauliköl verschmutzt. Offenbar lag / liegt eine Leckage an der Tiphydraulik vor.', '', 'Nordex N43,', '', '', '', ''],
                ["In allen Blättern tritt an einigen ``Ikea-Bolzen'' nach wie vor Fett/Öl aus. Eine qualifizierte Stellungnahme zur Zulässigkeit dieses Umstands ist erforderlich, sollte diese nicht bereits vorliegen.", '', 'Enercon,', '', '', '', ''],
                ['Die Belagstärke am vorderen Belagsatz gering. Ein Austausch des Belagsatzes ist erforderlich, um Schäden an der Bremsscheibe und verminderte Bremswirkung zu verhindern.', 'Enercon,', '', '', '', '', ''],
                ['An der Drehdurchführung ist eine deutliche Leckage vorhanden. Die Leckage sollte abgestellt werden, der betroffene Bereich sollte gereinigt werden.', '', 'Vestas,', '', '', '', ''],
                ['An der Hohlwelle hat sich etwas Korrosion gebildet. Es sollte ein Korrosionsschutz, beispielsweise Wachs o.Ä., aufgebracht werden.', 'Enercon,', '', '', '', '', ''],
                ['Am Anschluss des Getriebeölfilters sind Spuren einer leichten Leckage vorhanden, die abgestellt werden sollte.', 'Enercon,', '', '', '', '', 'Tade Jensen'],
                ['Die Bürsten zur Blitzstromableitung an der Hauptwelle sind mit Fett bedeckt, sodass nicht erkennbar ist, ob Kontakt besteht.', '', 'Nordex N43,', '', 'P', '', ''],
                ['Es sind keine augenscheinlichen Mängel feststellbar.', 'Enercon,', '', '', 'V', '', ''],
                ['Folgende Punkte müssen kurzfristig (binnen drei Monaten) erledigt werden:', '', '', '', 'S', '', ''],
                ['Um seine Pflichten erfüllen zu können, sollte er die fehlenden Nachweise und Dokumentationen vom Hersteller einholen. Weiterhin sollte er die Beseitigung der vorhandenen Mängel und Klärung der offenen Fragen veranlassen.', '', '', 'S', 'S', '', ''],
                ['Fettaustritt an den Blattbolzen', '', '', '', '-', '', ''],
                ['Die Prüfung beinhaltet den Prüfumfang einer wiederkehrenden Prüfung.', '', '', '', 'S', '', ''],
                ['Antriebsstrang', 'Enercon,', '', '', '', '', ''],
                ['Die Funktion der Flugbefeuerung wurde nicht geprüft.', '', '', '', '-', '', ''],
                ['Betriebsdaten wurden aus der Steuerung ausgelesen, Daten der Hauptkomponenten von Typenschildern.', '', '', 'S', 'S', '', ''],
                ['DIBt-Richtlinie für Windenergieanlagen', '', '', '-', '-', '', 'Tade Jensen'],
                ['Bericht zur Rotorblattprüfung Nr. XXX vom XXX.', '', '', '', '-', '', 'Tade Jensen'],
                ['Bericht zur Rotorblattinnenprüfung Nr. XXX vom XXX.', '', '', '', '-', '', 'Tade Jensen'],
                ['Rote Blattspitzen', '', '', '', '-', '', 'Tade Jensen'],
                ['Keine.', '', '', '', '-', '', 'Tade Jensen'],
                ['Der Zugang zur WEA war zum Zeitpunkt der Prüfung gut begehbar.', '', '', '', 'V', 'green', ''],
                ['Der Zugang zur WEA wird durch Bewuchs erschwert. Auch hier sollte der Betreiber Abhilfe schaffen.', '', '', '', '', '', ''],
                ['Es konnte aufgrund einer externen Abschaltung kein Probelauf unter Last durchgeführt werden.', '', '', '', 'I', '', ''],
                ['Es konnte aufgrund von Windmangel kein Probelauf durchgeführt werden. Auch die Ausrichtung zur Windrichtung konnte nicht überprüft werden.', '', '', '', '', '', 'Tade Jensen'],
                ['Gegenstand der Prüfung ist nur die in der WEA vorhandene Dokumentation. Die an den Betreiber gelieferte Doku dürfte viele der hier genannten Punkte ausräumen.', '', '', '', 'S', '', 'Tade Jensen'],
                ['Gegenstand der Prüfung war nur die in der WEA vorhandene bzw. vom Betreiber zur Verfügung gestellte Dokumentation.', '', '', '', 'S', '', 'Tade Jensen'],
                ['Am Beton sind innen ansonsten keine Auffälligkeiten feststellbar.', '', 'Beton,', '', 'I', '', ''],
                ['Am Beton sind innen ansonsten keine augenscheinlichen Mängel feststellbar.', '', 'Beton,', '', 'I', '', ''],
                ['Auf dem Fundament sind Spuren von Wassereintritt vorhanden, auf dem darüber liegenden Spalt im Fußflansch sind deutlich Laufspuren von Rost/Wasser vorhanden. Die Abdichtung des Flansches muss von außen verbessert werden. Zudem müssen die Schrauben im betroffenen Bereich ausgebaut und auf Korrosion geprüft werden. Korrodierte Schrauben müssen ersetzt werden.', '', '', '', 'P', '', ''],
                ['Das Fundament ist stellenweise feucht. Das Wasser tritt offenbar durch die Fuge zwischen Kellerwand und Bodenplatte ein. Eine Abdichtung ist erforderlich.', '', 'Beton,', '', 'P', '', ''],
                ['Es sind keine weiteren Auffälligkeiten vorhanden, die Kabel sind ansonsten ordentlich verlegt bzw. abgehängt.', '', '', '', 'I', '', ''],
                ['Die Abdeckungen der Stromschienen im Turm sollten mit einem Warnschild gekennzeichnet werden, da die Versorgungsschiene auch bei abgeschalteter Maschine unter Spannung steht.', '', 'Senvion,', '', '', '', 'Tade Jensen'],
                ['Ansonsten sind keine augenscheinlichen Mängel vorhanden.', '', '', '', 'I', 'yellow', ''],
                ['Ansonsten sind keine nennenswerten Auffälligkeiten vorhanden.', '', '', '', 'I', '', ''],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor.', '', 'Senvion,', '', '', '', 'Tade Jensen'],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor.', 'Vestas, Senvion,', '', '', 'I', 'yellow', ''],
                ['Ansonsten sind keine nennenswerten Auffälligkeiten vorhanden.', '', 'Enercon,', '', 'I', '', 'Tade Jensen'],
                ['Weitere Mängel liegen nicht vor, die Plattformen sind fest, sauber und trocken.', '', '', '', 'I', 'yellow', ''],
                ['Ansonsten sind keine Auffälligkeiten erkennbar, die Plattformen sind fest und ansonsten sauber und trocken.', '', '', '', 'I', '', ''],
                ['Die Lampe im Steuerschrank ist ohne Funktion.', '', '', '', '', '', ''],
                ['Der Leistungsschrank 3 lässt sich nicht öffnen, da die Tür unten klemmt. Eine Instandsetzung der Verriegelung ist erforderlich. Der Schrank konnte nicht kontrolliert werden.', '', '', '', '', '', ''],
                ['Eine Schraube in Sektion XXX hat einen ungewöhnlichen Klang. Die Vorspannung der markierten Schraube muss überprüft und ggf. korrogiert werden. Von dieser Verbindung wurden 100% der Schrauben geprüft.', '', '', '', '', '', ''],
                ['Eine Schaube in Sektion XXX konnte abgedreht werden. Die Schraube muss wieder angezogen werden. Die restlichen Schrauben der Verbindung (100% geprüft) zeigten keine Auffälligkeiten.', '', '', '', '', '', ''],
                ['An Blechen und Schweißnähten innen sind bei Stichproben ansonsten keine augenscheinlichen Mängel vorhanden.', '', '', '', 'I', '', ''],
                ['In allen Sektionen befinden sich im Turm unverschlossene Löcher, durch die Wasser eindringt. Die Löcher müssen verschlossen werden.', '', '', '', '', '', ''],
                ['Auch ansonsten sind keine augenscheinlichen Mängel feststellbar.', '', 'Stahlblech,', '', 'V', '', 'Tade Jensen'],
                ['Ansonsten sind keine augenscheinlichen Mängel vorhanden.', '', 'Stahlblech,', '', 'I', '', ''],
                ['Die Treppe ist provisorisch auf einem Kantholz abgestützt. Die Punktfundamente müssen noch hergestellt werden.', '', '', '', '', '', ''],
                ['An dem kleinen Lichtgitter im Boden des Außenpodestes fehlen nach wie vor die Befestigungsklemmen.', '', '', '', '', '', 'Tade Jensen'],
                ['Ansonsten sind keine augenscheinlichen Mängel an Tür und Eingangsbereich zu erkennen.', '', '', '', 'I', 'yellow', ''],
                ['Ansonsten sind keine Auffälligkeiten an Tür und Eingangsbereich zu erkennen.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Es liegen keine augenscheinlichen Mängel vor.', '', 'Beton,', '', 'V', '', ''],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor', '', 'Beton,', '', 'I', '', ''],
                ['Es liegen keine augenscheinlichen Mängel vor, Füße, Befestigung und Gehäuse sind soweit erkennbar in Ordnung.', '', 'Nortank AF 1987 A/S,', '', 'V', '', ''],
                ['An den Kabeln der Luftspaltschalter sind einige Kabelbinder gerissen, die Kabel müssen wieder sicher befestigt werden.', '', 'Enercon,', '', 'P', '', 'Tade Jensen'],
                ['Überdrehzahltest: Ein Nachweis (Protokoll) über die Durchführung fehlt an der WEA.', 'Senvion,', '', '', 'P', '', ''],
                ['Bisher wurden an der Anlage keine Wartungen oder Instandhaltungsmaßnahmen durchgeführt bzw. in der Anlage dokumentiert.', '', '', '', 'I', '', ''],
                ['Die Beschilderungen lösen sich teilweise ab. Nacharbeit ist erforderlich.', '', '', '', 'P', '', ''],
                ['Außen am Turm und in der Trafostation sind Hinweisschilder bzw. dessen Beschriftung teilweise verblasst.', '', '', '', '', '', 'Tade Jensen'],
                ['Die Zahnflanken des Azimutdrehkranzes zeigen ein normales Laufbild und sind ausreichend geschmiert. Die Ritzel sind durch eine Abdeckung nicht einsehbar.', '', '', '', 'V', '', ''],
                ['Die Verzahnung des Zahnkranzes ist nur eingeschränkt einsehbar, der einsehbare Bereich zeigt keine Auffälligkeiten. Die Verzahnung der Ritzel ist nicht einsehbar.', '', 'Vestas V52 - 850 kW,', '', 'I', '', 'Tade Jensen'],
                ['An den Dachaufbauten liegen keine augenscheinlichen Mängel vor.', '', '', '', 'V', '', ''],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor.', '', '', '', 'I', 'yellow', ''],
                ['Weitere Auffälligkeiten sind nicht feststellbar.', '', 'Senvion,', '', 'I', '', ''],
                ['Ansonsten sind keine Auffälligkeiten erkennbar.', 'Enercon,', '', '', 'I', '', ''],
                ['Es liegen keine weiteren augenscheinlichen Mängel vor, die Funktion ist einwandfrei und es sind keine Undichtigkeiten zu erkennen.', '', 'Enercon,', '', 'I', 'green', ''],
                ['Es liegen keine weiteren augenscheinlichen Mängel vor, die Funktion ist einwandfrei.', 'Senvion, Vestas,', '', '', 'I', '', ''],
                ['Ansonsten sind die Kabel sorgfältig verlegt bzw. abgehängt, es liegen keine weiteren Auffälligkeiten vor.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor, die Kabel sind sorgfältig verlegt bzw. abgehängt.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Ansonsten sind keine augenscheinlichen Mängel vorhanden, die Funktion ist einwandfrei.', '', '', '', 'I', 'yellow', ''],
                ['Ansonsten sind keine nennenswerten Auffälligkeiten vorhanden, die Funktion ist einwandfrei.', '', '', '', 'I', '', ''],
                ['Ansonsten liegen keine Auffälligkeiten vor.', '', '', '', 'I', '', ''],
                ['Ansonsten sind keine augenscheinlichen Mängel an Schläuchen, Anschlüssen, Behältern und Wärmetauschern vorhanden. Es sind keine Leckagen festzustellen.', '', 'Vestas,', '', 'I', '', ''],
                ['Ansonsten sind keine Auffälligkeiten erkennbar, keine Zeichen von eingedrungenem Wasser.', '', '', '', 'I', '', ''],
                ['Zur Halterung der Dachsegmente wurden teilweise Dämpfer benutzt, dessen Zylinder abgerundete Ecken aufweisen (Bild links). Zur Feststellung des Daches im offenen Zustand muss die Stirnfläche des Zylinders auf einem Rohr aufliegen. Bei den Dämpfern mit abgerundeten Ecken rutschen die Zylinder leicht von der Kante des Rohrs ab (Bild rechts), sodass das Dachsegment herabfallen bzw. nur auf dem verbleibenden Zylinder aufliegen kann. Die Dämpfer mit abgerundetem Zylinder sollten gegen Zylinder mit Kante (Bild unten) ausgetauscht werden.', '', 'NEG Micon,', '', '', '', ''],
                ['Ansonsten sind keine Auffälligkeiten an Maschinenträger und tragenden Elementen erkennbar. Bei Stichproben sind keine Risse oder Korrosion an Blechen und Schweißnähten vorhanden.', '', '', '', 'I', '', ''],
                ['Ansonsten liegen an Maschinenträger und tragenden Elementen keine augenscheinlichen Mängel vor. Es ist keine Korrosion oder Fehlstellen an den einsehbaren Bereichen des Maschinenträgers und des Hilfsrahmens zu erkennen.', '', '', '', 'I', '', ''],
                ['Im Maschinenhaus befindet sich unverbautes Material, das montiert oder entfernt werden muss.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Im Maschinenhaus befindet sich ein leerer Ölkanister.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Die Rotorarretierung arbeitet einwandfrei, ansonsten sind keine Auffälligkeiten feststellbar.', 'Enercon,', '', '', 'I', '', ''],
                ['Die Bremsscheibe ist durch Fett verschmutzt und muss gereinigt werden. Zudem muss eine erneute Verschmutzung der Bremsscheibe verhindert werden.', '', 'Enercon,', '', 'P', '', 'Tade Jensen'],
                ['Die Bremsscheibe ist verschmutzt und muss gereinigt werden.', '', 'Enercon,', '', 'P', '', 'Tade Jensen'],
                ['Ansonsten sind keine Auffälligkeiten erkennbar.', '', '', '', 'I', '', ''],
                ['Der Azimutumrichterschrank konnte nicht kontrolliert werden, da sich der Verschluss unten links nach wie vor nicht mit normaler Handkraft öffnen lässt. Der Verschluss muss gangbar gemacht werden.', '', '', '', '', '', ''],
                ['Der Trafo befindet sich in der Gondel, die Mittelspannungsschaltanlage steht auf dem Fundament im Turm.', '', '', '', 'I', '', ''],
                ['Die Komponenten der Trafostation wurden nicht überprüft, da kein Schlüssel vorhanden war.', '', '', '', 'I', '', ''],
                ['Ansonsten sind keine Auffälligkeiten feststellbar, der Druck des SF$_\\text{6}$ Gases ist in Ordnung und die Felder sind beschriftet.', '', '', '', 'I', '', 'Tade Jensen'],
                ['Es fehlen Spannungsanzeiger, die nach Meinung des Unterzeichners zur Schaltanlage gehören. Es ist nicht klar, wie ansonsten die Spannungsfreiheit festgestellt werden soll.', '', '', '', 'I', 'green', ''],
                ['An einer Tür des Stationsgebäudes ist nach wie vor Korrosion vorhanden.', '', '', '', 'I', '', ''],
                ['Im Bereich der Kabeleinführung steht Wasser in der Station, eine Abdichtung der Kabeleinführung wird dringend empfohlen.', '', '', '', 'E', '', 'Tade Jensen'],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor, der Trafo ist ansonsten sauber und trocken, die Anschlüsse zeigen keine Auffälligkeiten.', '', '', '', 'I', 'yellow', ''],
                ['Ansonsten liegen keine Auffälligkeiten vor, der Trafo ist ansonsten sauber und trocken, die Anschlüsse zeigen keine Auffälligkeiten.', '', '', '', 'I', '', ''],
                ['Das Rolltor des Traforaumes schleift nach wie vor beim Öffenn und Schließen an der Schaltanlage und muss korrekt montiert werden.', '', '', '', '', '', 'Tade Jensen'],
                ['Es sind keine augenscheinlichen Mängel vorhanden.', '', '', '', 'V', '', ''],
                ['In der Anlage befindet sich keine geprüfte PSA.', '', '', '', 'I', '', ''],
                ['In der Anlage befinden sich zwei Satz PSA. Diese haben allerdings die Ablegereife erreicht und sollten ersetzt werden.', '', '', '', 'E', '', ''],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor.', '', '', '', 'I', '', ''],
                ['Ansonsten liegen am Lift keine augenscheinlichen Mängel vor, ist die Funktion einwandfrei.', '', '', '', 'I', 'yellow', ''],
                ['Ein Notfallplan fehlt im Lift.', '', '', '', '', '', ''],
                ['Der Blitzschutz des Rotorsystems ist ohne Auffälligkeiten.', '', 'Senvion,', '', 'V', '', ''],
                ['An den Blitzableiteinrichtungen liegen ansonsten keine augenscheinlichen Mängel vor.', '', '', '', 'I', 'yellow', ''],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor. Am Guss und an der Beschichtung sind keine augenscheinlichen Mängel erkennbar.', '', '', '', '', '', 'Tade Jensen'],
                ['Nabe und Blattverschraubungen konnten nicht geprüft werden, da dieser Bereich mit der vorhandenen PSA nicht sicher erreichbar gewesen ist.', '', '', '', '', '', ''],
                ['Die Zentralschmieranlage ist fettverschmiert, offenbar liegt eine Leckage vor. Abhilfe ist erforderlich.', '', '', '', '', '', ''],
                ['An der Zentralschmieranlage tritt nach wie vor etwas Fett aus und verschmutzt die Nabe im Bereich von Blatt A. Die Leckage muss beseitigt werden und die verschmutzten Bereiche müssen gereinigt werden.', '', '', '', '', '', ''],
                ['Bei der Kontrolle der Rotorblätter von Spinner, Nabe und Maschinenhaus aus sind keine Auffälligkeiten vorhanden.', '', '', '', 'V', '', 'Tade Jensen'],
                ['Bei der Kontrolle der Rotorblätter von der Dachluke des Generators aus sind keine Auffälligkeiten vorhanden.', '', 'Enercon,', '', 'V', '', 'Tade Jensen'],
                ['Ansonsten liegen an der Tiphydraulik keine erkennbaren Mängel vor, die Funktion ist einwandfrei.', '', 'Nortank AF 1987 A/S,', '', 'I', '', ''],
                ['Ansonsten sind am Spinner keine nennenswerten Auffälligkeiten erkennbar.', '', '', '', 'I', '', ''],
                ['An der Anlage ist kein Spinner verbaut.', '', '', '', '', '', ''],
                ['Ansonsten sind an den Steuerschränken am Rotor keine Auffälligkeiten erkennbar (Stichprobe Schränke Blatt C).', '', 'Enercon,', '', 'I', '', 'Tade Jensen'],
                ['Ansonsten liegen keine augenscheinlichen Mängel vor. Die Kabel sind ordentlich verlegt, der Schaltschrank im Rotor (nicht geöffnet) zeigt keine augenscheinlichen Mängel.', '', 'Vestas,', '', 'I', '', 'Tade Jensen'],
                ['Von Turm, Maschinenhaus und Nabe aus sind keine augenscheinlichen Mängel festellbar.', '', 'Nordex N43,', '', 'V', '', ''],
                ['Ansonsten sind von Turm, Maschinenhaus und Nabe aus keine Auffälligkeiten festellbar.', '', 'Nordex N43,', '', 'I', '', ''],
                ['In der Nabe befindet sich Wasser, das an der spinnerlosen Anlage offenbar durch die Blattbolzen von Blatt B eindringt. Das Wasser muss entfernt und die Abdichtung der Nabe verbessert werden, um elektrische Komponenten zu schützen und Korrosion zu verhindern.', 'Enercon,', '', '', '', '', ''],
                ['An einem Pitchlager fehlt nach wie vor eine Verschraubung. Sie muss eingesetzt werden.', '', '', '', '', '', ''],
                ['Ansonsten sind an der Bremse keine augenscheinlichen Mängel vorhanden. Die Bremsscheibe ist weitestgehend glatt und ohne Riefen und Korrosion, die Bremssättel zeigen keine Leckagen, die Funktion ist einwandfrei.', 'Enercon,', '', '', 'I', '', ''],
                ['Die Bremse an der Abtriebswelle des Getriebes ist durch eine Abdeckung nicht einsehbar. Die Funktion der Bremse während der Prüfung ist in Ordnung.', 'Enercon,', '', '', 'I', '', ''],
                ['Ansonsten sind keine Auffälligkeiten erkennbar.', '', 'Vestas,', '', 'I', '', ''],
                ['Die Drehdurchführung ist wegen einer Abdeckung nicht einsehbar.', '', 'Vestas,', '', '', '', ''],
                ['Die elastischen Elemente der Drehmomentstützen sind nach wie vor teilweise rissig bzw. beschädigt.', '', 'Nordex N43,', '', '', '', ''],
                ['Das Rad und das Ritzel der schnellen Stufe sind soweit erkennbar in einem guten altersgemäßen Zustand.  Es sind keine Risse oder Ausbrüche und keine Anzeichen für Geometriefehler zu erkennen.', 'Enercon,', '', '', 'V', '', ''],
                ['Der Ölstand wird nach längerem Stillstand leicht unterhalb der Min-Markierung angezeigt und sollte korrigiert werden.', 'Enercon,', '', '', '', '', ''],
                ['Der Ölstand kann wegen der Verunreinigung des Schauglases nicht klar erkannt werden.', 'Enercon,', '', '', '', '', ''],
                ['Es liegen keine augenscheinlichen Mängel am Lager und am Lagergehäuse vor, der Fettaustritt am Hauptlager scheint im Bereich des Üblichen.', '', 'Vestas,', '', 'V', '', ''],
                ['Ansonsten liegen keine augenscheinlichen Mängel an Hauptlager und Welle vor, der Fettaustritt am Hauptlager scheint im Bereich des Üblichen.', 'Enercon,', '', '', 'I', '', ''],
                ['Die Kupplung ist wegen einer vollständigen Abdeckung nicht einsehbar.', 'Enercon,', '', '', 'I', '', ''],
                ['Im Maschinenhaus befinden sich ungenutzte Schmieranschlüsse der Kupplung.', '', 'Nordex N43,', '', 'I', '', ''],
                ['Die bei der letzten Prüfung 2020 bemängelten Punkte, die hier nicht aufgeführt sind, wurden behoben. Es wird davon ausgegangen, dass geforderte Stellungnahmen erbracht worden sind.', '', '', '', 'S', '', 'Tade Jensen'],
                ['Austausch des verschlissenen Belagsatzes', '', '', '', '-', '', ''],
                ['Für den langjährigen und sicheren Betrieb der Anlage ist der Betreiber verantwortlich. Voraussetzung hierfür ist insbesondere die Durchführung und Dokumentation der Wartungen gemäß Wartungspflichtenheft.', '', '', '', 'S', '', ''],
                ['Dem Auftragnehmer sind die vertraglichen Details zwischen Betreiber und WEA-Hersteller bzw. Wartungsunternehmen i.d.R. nicht im Detail bekannt. Die Zuweisung der Verantwortlichkeiten für die Abstellung der Mängel ggü. weiteren Parteien obliegt dem Auftraggeber.', '', '', 'S', 'S', '', ''],
                ['Insbesondere sind Stellungnahmen/Nachweise zu folgenden Punkten vom Hersteller zu erbringen, sollten diese nicht bereits vorliegen:', '', '', '', 'S', '', 'Tade Jensen'],
                ['Maximal zulässige Temperatur an den Niederspannungskerzen des Trafos', '', '', '', '-', '', 'Tade Jensen'],
                ['Eine wiederkehrende Prüfung ist im MONAT JAHR bzw. bei Vorliegen eines gültigen Wartungsvertrages im MONAT, JAHR fällig.', '', '', '', 'S', '', ''],
                ['Eine wiederkehrende Prüfung ist im MONAT JAHR fällig.', '', '', '', 'S', '', ''],
                ['Weiterer Betrieb', '', '', '', '', '', ''],
                ['Ein Probelauf konnte nicht durchgeführt werden.', '', '', '', '*', '', ''],
                ['Aufgrund von Arbeitsschutzbedenken wurde kein Probelauf durchgeführt.', '', '', '', '-', '', ''],
                ['Aufgrund einer externen Abschaltung konnte kein Probelauf durchgeführt werden.', '', '', '', '-', '', ''],
                ['\\begin{itemize}|\\item{\\textbf{Kennzeichnung} der WEA und Komponenten: Prüfung auf Vollständigkeit und Plausibilität}|\\item{\\textbf{Dokumentation}: Prüfung auf Vollständigkeit sowie stichprobenartig auf Plausibilität}|\\item{Bisher durchgeführte \\textbf{Instandhaltungsmaßnahmen} bzw. Prüfungen: Kontrolle und Beurteilung anhand der vorhandenen Dokumentation}|\\item{\\textbf{Betriebsverhalten} der WEA: Prüfung auf außergewöhnliche Zustände, z.B. Geräusche, Temperaturen, Leistungsverhalten, Windnachführung, Schwingungen, Vibrationen}|\\item{Elektrotechnische Einrichtungen des \\textbf{Betriebsführungs-} und \\textbf{Sicherheitssystems}: Funktionsprüfungen}|\\item{\\textbf{Netzanbindung}: Sichtprüfung der Komponenten}|\\item{Elektrotechnische Systeme (z. B. \\textbf{Schaltschränke}): Sicht- und Funktionsprüfung}|\\item{\\textbf{Schutzeinrichtungen} für Personal einschließlich PSA, Steigeinrichtungen, ggf. Lift: Prüfung auf Vorhandensein, Funktionsfähigkeit und mögliche Personengefährdung}|\\item{\\textbf{Fundament}: Sichtprüfung und ggf. Abklopfen auf Schäden z.B. Korrosion, Risse, Abplatzungen, Hohlstellen im Beton}|\\item{\\textbf{Turm}: Sichtprüfung vom Boden und der Steigleiter z.B. auf Korrosion, Risse, Ausbrüche, sonstige Schäden, Sicht- und Lockerheitskontrolle der Schraubverbindungen}|\\item{Komponenten der \\textbf{Gondel} und des \\textbf{Nabensystems}: Sichtprüfung z.B. auf Beschädigungen, Risse, Verschleiß, Korrosion, Dichtheit, Schmierzustand, Sicht- und Lockerheitskontrolle tragender Schraubverbindungen}|\\end{itemize}', '', '', 'RAW', 'RAW', '', 'Tade Jensen'],
                ['\\textbf{Berichte früherer Prüfungen}: Einsichtnahme, Kontrolle auf Mängelbeseitigung an der WEA. Hier: NAME, 8.2 Ingenieurbüro Jensen NF, DATUM', '', '', '', '-', '', ''],
                ['Allgemeine anerkannte Regeln der Technik', '', '', '-', '-', '', 'Tade Jensen'],
                ['Richtlinien für Auslegung, Aufstellung und Betreiben von Windkraftanlagen', '', '', '-', '-', '', 'Tade Jensen'],
                ['Fledermausabschaltung', '', '', '', '-', '', 'Tade Jensen'],
                ['Flight Manager', '', '', '', '-', '', 'Tade Jensen'],
                ['Monitoringsystem Pitchlager', '', 'Senvion,', '', '-', '', 'Tade Jensen'],
                ['Rote Befeuerung als Nachtkennzeichnung mit versetzten Gefahrenfeuern und Ersatzspannungsquelle', '', '', '', '-', '', 'Tade Jensen'],
                ['Befeuerungsring am Turm', '', '', '', '-', '', 'Tade Jensen'],
                ['Niederschlagsensor', '', '', '', '-', '', 'Tade Jensen'],
                ['Serrations an den Rotorblättern', '', '', '', '-', '', 'Tade Jensen'],
                ["Schalloptimierung lt. Aufkleber ``Turbine-data'' im Steuerschrank", '', 'Enercon,', '', '-', '', 'Tade Jensen'],
                ['Schattenabschaltung', '', '', '', '-', '', 'Tade Jensen'],
                ['Sichtweitenmessgerät für die Flugbefeuerung', '', '', '', '-', '', 'Tade Jensen'],
                ['Weiße Tageskennzeichnung', '', '', '', '-', '', 'Tade Jensen'],
                ['Roter Ring am Turm', '', '', '', '-', '', 'Tade Jensen'],
                ['Roter Ring am Turm und am Maschinenhaus', '', '', '', '-', '', 'Tade Jensen'],
                ['Rot-Weiß-Rote Blattspitzen', '', '', '', '-', '', 'Tade Jensen'],
                ['Folgende Punkte müssen umgehend (binnen eines Monats) erledigt werden:', '', '', '', 'S', '', ''],
                ['Folgende Punkte müssen vor Wiederinbetriebnahme der Anlage erledigt werden:', '', '', '', 'S', '', ''],
                ['Aus technischer Sicht ist die Beseitigung der genannten Mängel im Rahmen der nächsten Wartung ausreichend. Beschichtungs- und Abdichtarbeiten dürfen nur bei geeigneter Witterung ausgeführt werden.', '', '', 'S', 'S', '', 'Tade Jensen'],
                ['Aus technischer Sicht ist die Beseitigung der restlichen| Mängel im Rahmen der nächsten Wartung ausreichend. Beschichtungs- und Abdichtarbeiten dürfen nur bei geeigneter Witterung ausgeführt werden.', '', '', '', 'S', '', 'Tade Jensen'],
                ['Die Vorspannung der markierten Blattbolzen muss überprüft und ggf. korrigiert werden.', '', '', '', '-', '', ''],
                ['Austausch der leeren Fettbehälter an den Hauptlagern', '', '', '', '-', '', ''],
                ['Durchführung des Überdrehzahltests', '', '', '', '-', '', ''],
                ['Die Schmierung der Azimutverzahnung muss verbessert werden.', '', '', '', '-', '', ''],
                ['Die bei der letzten Prüfung 2022 bemängelten Punkte, die hier nicht aufgeführt sind, wurden behoben.', '', '', '', 'S', '', 'Tade Jensen'],
                ['Die bei der letzten Prüfung 2021 bemängelten Punkte, die hier nicht aufgeführt sind, wurden behoben oder werden für eine Anlage dieses Alters nicht mehr als relevant eingestuft.', '', '', '', 'S', '', 'Tade Jensen'],
                ['Für den langjährigen und sicheren Betrieb der Anlage ist der Betreiber verantwortlich.', '', '', 'S', 'S', '', ''],
                ['Fettaustritt zwischen Hauptwelle und Sitzring des Hauptlagers', '', '', '', '-', '', ''],
                ['Risse im Fundament', '', '', '', '-', '', ''],
                ['Tragfähigkeit der Abstützung im Spannkeller', '', 'Beton,', '', '', '', 'Tade Jensen'],
                ['Qualifizierte Stellungnahme/QS-Dokumentation zur Schweißnaht in im Übergangsstück', '', '', '', '-', '', 'Tade Jensen'],
                ['Die Prüfung beinhaltet - in Verbindung mit einer Rotorblattprüfung - den Prüfumfang einer wiederkehrenden Prüfung.', '', '', 'S', 'S', '', ''],
                ['Schutzausrüstung und Arbeitssicherheit', '', '', '', '', '', ''],
                ['Betriebscharakteristik', '', '', '', '', '', ''],
                ['Leckagen Getriebe und Bremse; Korrosion an Hauptwelle, Bremse, Kupplung und Generator.', 'Enercon,', '', '', '*', '', ''],
                ['Es ist keine geprüfte PSA oder ein Hinweis auf dessen Lagerort in der Anlage vorhanden.', '', '', '', '*', '', ''],
                ['Laute, schlagende Geräusche aus dem Getriebe', '', '', '', '*', '', ''],
                ['Quietschgeräusche während der Windnachführung.', '', '', '', '*', '', ''],
                ['Vereinzelt wurden Wartungen nicht durchgeführt bzw. nicht dokumentiert oder nicht turnusgemäß durchgeführt.', '', '', '', '*', '', ''],
                ['Es wurden nur wenige Wartungen durchgeführt bzw. in der Anlage dokumentiert.', '', '', '', '*', '', ''],
                ['Der Vibrationsschalter fehlt.', '', '', '', '*', '', ''],
                ['Die Verzahnung des Pitchsystems weist deutlichen Verschleiß auf.', '', '', '', '*', '', 'Tade Jensen'],
                ['Die Risse in den Querträgern im Spannkeller beeinträchtigen die Tragfähigkeit der Bodenplatte, die das E-Modul trägt.', '', 'Beton,', '', '', '', 'Tade Jensen'],
                ['Die Risse in den Querträgern im Spannkeller können die Tragfähigkeit der Bodenplatte, die das E-Modul trägt, beeinträchtigen.', '', 'Beton,', '', '*', '', 'Tade Jensen'],
                ['Die korrekte Vorspannung der auffälligen Ankerbolzen muss gewährleistet werden.', '', '', '', '*', '', ''],
                ['Die Anlage kann mit dem geschädigten Lager zustandsorientiert betrieben werden.', '', '', '', '*', '', ''],
                ['Die Untersuchung des Antriebsstrangs ergab keine wesentlichen Auffälligkeiten.', 'Enercon,', '', '', '*', '', ''],
                ['Die Untersuchung des Antriebsstrangs ergab leichte Auffälligkeiten.', 'Enercon,', '', '', '*', '', ''],
                ['Die Untersuchung des Antriebsstrangs ergab einen wesentlichen Mangel.', 'Enercon,', '', '', '*', '', ''],
                ['Die Prüfung ergab keine offensichtlichen Gefährdungen oder Mängel am Personenschutz.', '', '', '', '*', '', ''],
                ['Die Prüfung ergab Gefährdungen oder Mängel am Personenschutz.', '', '', '', '*', '', ''],
                ['Die Anlage zeigte im Betrieb keine Auffälligkeiten.', '', '', '', '*', '', 'Tade Jensen'],
                ['Die Anlage zeigte im Betrieb Auffälligkeiten.', '', '', '', '*', '', 'Tade Jensen'],
                ['Die bisher durchgeführten Instandhaltungsmaßnahmen und Prüfungen entsprechen weitestgehend den Vorgaben und wurden soweit erkennbar sorgfältig durchgeführt.', '', '', '', '*', '', ''],
                ['Die bisher durchgeführten Instandhaltungsmaßnahmen und Prüfungen weisen nur leichte Abweichungen von den Vorgaben auf.', '', '', '', '*', '', ''],
                ['Die bisher durchgeführten Instandhaltungsmaßnahmen und Prüfungen weisen Abweichungen von den Vorgaben oder Mängel auf.', '', '', '', '*', '', ''],
                ['Die Prüfung der Sicherheitssysteme ergab keine Mängel.', '', '', '', '*', '', ''],
                ['Die Sicherheitssysteme weisen Mängel auf.', '', '', '', '*', '', ''],
                ['Die Standsicherheit der Anlage ist durch die gefundenen Mängel nicht beeinträchtigt.', '', '', '', '*', '', ''],
                ['Die Standsicherheit der Anlage ist derzeit nicht gefährdet oder beeinträchtigt.', '', '', '', '*', '', ''],
                ['Die Standsicherheit der Anlage kann durch die gefundenen Mängel beinträchtigt sein.', '', '', '', '*', '', ''],
                ['Die Anlage kann bis zur fristgerechten Beseitigung der Mängel und Beantwortung der Fragen ohne Einschränkungen weiter betrieben werden.', '', '', '', '*', '', ''],
                ['Die WEA kann nur mit Einschränkungen weiter betrieben werden.', '', '', '', '*', '', ''],
                ['Gesamteindruck der WEA', '', '', '', '', '', ''],
                ['Insgesamt macht die Anlage einen guten Eindruck.', '', '', '', '*', '', ''],
                ['Insgesamt macht die Anlage einen zufriedenstellenden Eindruck.', '', '', '', '*', '', ''],
                ['Insgesamt macht die Anlage einen nicht zufriedenstellenden Eindruck.', '', '', '', '*', '', ''],
                ['Der Zustand des Fundamentes verhindert einen besseren Eindruck.', '', '', '', '*', '', ''],
                ['Die Vielzahl der Mängel verhindert einen besseren Eindruck.', '', '', '', '*', '', 'Tade Jensen'],
                ['Instandhaltung und Prüfungen', '', '', '', '', '', ''],
                ['Die Anlage weist wenige Mängel auf.', '', '', '', '*', '', ''],
                ['Die Anlage weist Mängel auf. Die Mängel sind nicht schwerwiegend.', '', '', '', '*', '', ''],
                ['Die Anlage weist einen gravierenden Mangel auf.', '', '', '', '*', '', ''],
                ['Die Anlage weist viele Mängel auf.', '', '', '', '*', '', ''],
                ['Sicherheitssysteme', '', '', '', '', '', ''],
                ['Sonstige Bemerkungen', '', '', '', '', '', ''],
                ['Standsicherheit', '', '', '', '', '', ''],
                ['Die Anlage wurde nicht wieder in Betrieb gesetzt. Erst nach Beseitigung des Spaltes am untersten Flansch und Austausch und Anziehen der Turmschrauben darf die WEA wieder betrieben werden.', '', '', '', '*', '', ''],
                ['Die Komponenten des Traforaums konnten nicht begutachtet werden, da keine schaltberechtigte Person vor Ort war.', '', '', '', '-', '', ''],
                ['Die Komponenten des Traforaums konnten nicht begutachtet werden, da kein Schlüssel vorhanden war.', '', '', '', '-', '', ''],
                ['Die separate Betonstation mit MS-Transformator und Schaltanlage konnte nicht geprüft werden, da kein Schlüssel vorhanden war.', '', '', '', '-', '', ''],
                ['Aufgrund von Windmangel konnte kein Probelauf durchgeführt werden.', '', '', '', '-', '', ''],
                ['Aufgrund von technischen Problemen konnte kein Probelauf durchgeführt werden.', '', '', '', '-', '', ''],
                ['Durchgeführte Prüfungen bzw. geprüfte Elemente / Baugruppen, soweit vorhanden und zugänglich:', '', '', 'S', 'S', '', ''],
                ['\\textbf{Probelauf} bei XXX\\,m/s und XXX\\,kW bei Anwesenheit im Maschinenhaus', '', '', '', '-', '', ''],
                ['\\textbf{Probelauf} XXX\\,m/s, XXX\\,kW bei Anwesenheit im Maschinenhaus. Ein Probelauf unter Leistung war wegen einer externen Abschaltung nicht möglich.', '', '', '', '-', '', ''],
                ['\\textbf{Probelauf} XXX\\,m/s, XXX\\,kW bei Anwesenheit im Maschinenhaus. Ein Probelauf unter Leistung war wegen Windmangels nicht möglich.', '', '', '', '-', '', ''],
                ['\\textbf{Probelauf} bei ca. XXX\\,m/s und XXX\\,kW. Wegen Sicherheitsbedenken wurde der Problelauf bei Anwesenheit im Turmfuß durchgeführt.', '', '', '', '-', '', ''],
                ['Prüfung der \\textbf{Rotorblätter innen} aus unmittelbarer Nähe, soweit zugänglich', '', '', '', '-', '', 'Tade Jensen']],
            'index_names': [
                'chapter', 'title', 'variantnr'],
            'column_names': [
                None]}

def get_default_chapter_order():
    return {
            'Allgemeine Daten|Prüfbericht|Zugehörige Dokumente': [
                'Introsatz',
                'Prüfbericht Rotorblätter',
                ],
            'Anlagendaten|Zusätzliche Ausrüstung der Anlage': [
                'Tageskennzeichnung',
                'Nachtkennzeichnung',
                'Sichtweitenmessgerät',
                'Schattenabschaltung',
                'Niederschlagssensor',
                'Fledermausabschaltung',
                'Schalloptimierung',
                'Flight Manager',
                'RBL Extras',
                'Monitoringsystem',
                'Eiserkennung',
                'keine',
                ],
            'Prüfungsgrundlagen|Prüfungsgrundlage': [
                'Regeln der Technik',
                'Richtlinien WEA',
                'DIBt Richtlinie',
                ],
            'Prüfungsgrundlagen|Prüfliste': [
                'Intro',
                'Standard Prüfliste',
                'alte Berichte',
                'Probelauf',
                'RBLi',
                'Info Datenauslese',
                ],
            'Prüfungsgrundlagen|Nicht durchgeführte Prüfungen': [
                'kein Probelauf',
                'Traforaum',
                'Flugbefeuerung',
                ],
            'Prüfbemerkungen|Kennzeichnung': [
                'Erste Hilfe Schild i.O.',
                'äußerliche Mängel Kennzeichnung',
                ],
            'Prüfbemerkungen|Dokumentation': [
                'nur Doku in Anlage betrachtet',
                'Bedienungsanleitung i.O.',
                ],
            'Prüfbemerkungen|Instandhaltung': [
                'keine Wartungen',
                'kein Überdrehzahltest',
                'Arbeiten nachvollziehbar dokumentiert',
                ],
            'Prüfbemerkungen|Betriebsverhalten und Sicherheitssysteme': [
                'kein Probelauf',
                'Abschalt-Windgeschwindigkeit',
                ],
            'Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz': [
                'PSA nicht i.O.',
                'Abseilgerät i.O.',
                ],
            'Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz|Leiter und Steigschutz': [
                'Abrieb',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|PSA, Aufstieg und Arbeitsschutz|Servicelift': [
                'kein Notfallplan',
                'Nebenteil auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Netzanbindung': [
                'Ort Trafo + MS-SA',
                'nicht geprüft',
                ],
            'Prüfbemerkungen|Netzanbindung|Zugang / Kennzeichnung / Bedienung': [
                'Tür auffällig',
                'Kennzeichnung auffällig',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Netzanbindung|Trafo': [
                'Anschlüsse auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Netzanbindung|Schaltanlage': [
                'keine Spannungsanzeiger',
                'Beschriftung nicht i.O.',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Netzanbindung|Sonstiges': [
                'Station auffällig',
                'Schmauchspuren',
                ],
            'Prüfbemerkungen|Außenbereich': [
                'Kranstellfläche belegt',
                'Zugang i.O.',
                'Zugang nicht i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Fundament': [
                'Dichtung nicht i.O.',
                'Wasser auf Fundament',
                ],
            'Prüfbemerkungen|Fundament und Turm|Turm außen': [
                'Beschichtungsschäden Schweißnaht',
                'unbefestigte Teile',
                'provisorischer Stand',
                ],
            'Prüfbemerkungen|Fundament und Turm|Tür und Eingangsbereich': [
                'Anbauteile Tür auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Schaltschränke': [
                'Brandlast',
                'defekte Teile',
                ],
            'Prüfbemerkungen|Fundament und Turm|Kabel / Elektrische Komponenten': [
                'mangelhafte Kennzeichnung',
                'Aufhängung auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Luftführung / Kühlung der elektrischen Einrichtungen': [
                'Nebenteil auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Kühlung der elektrischen Einrichtungen': [
                'Schlauch auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Plattformen / Einbauteile': [
                'Absturzgefahr',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Betonteil': [
                'Abplatzungen',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Übergangsstück Beton-Stahl': [
                'Korrosion',
                'ansonsten i.O.',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Sektionsstöße und Verbindungsplatten': [
                'Dichtung fehlerhaft',
                'ansonsten i.O.',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Schrauben und Flansche': [
                'ungewöhnlicher Klang',
                'Flansch feucht',
                ],
            'Prüfbemerkungen|Fundament und Turm|Schweißnähte und Blechoberflächen': [
                'unverschlossene Löcher',
                'Korrosion Schweißnaht',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Fundament und Turm|Korrosion / Beschichtung': [
                'Beschichtungsdicke gering',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Azimutlagerung / Windnachführung': [
                'Tragbild i.O.',
                'Antriebe ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Maschinenträger und tragende Elemtente': [
                'Fehlstelle',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Schaltschränke in der Gondel': [
                'ungeöffneter Schrank',
                'Abdichtung nicht i.O.',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Kabel / Beleuchtung / Einbauteile': [
                'Kabel beschädigt',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Lastenwinde': [
                'Nebenteil beschädigt',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Hydraulik (Rotorarretierung)': [
                'Korrosion',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Hydraulik': [
                'Leckage',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Lüfter / Luftführung Maschine': [
                'Geräusche',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Podeste / Einbauteile / Hinweisschilder': [
                'Abdeckung auffällig',
                'unverbautes Material',
                ],
            'Prüfbemerkungen|Maschinenhaus|Rotorbremse': [
                'Funktion auffällig',
                'Öl auf Bremsscheibe',
                ],
            'Prüfbemerkungen|Maschinenhaus|Rotorarretierung': [
                'ansonsten i.O.',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Maschinenhausverkleidung': [
                'falsche Dämpfer',
                'Befestigung auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Maschinenhaus|Dachaufbauten': [
                'Funktion auffällig',
                'ansonsten i.O.',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Triebstrang|Hauptlager und Hauptwelle': [
                'Blitzableitung auffällig',
                'ansonsten i.O.',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Triebstrang|Getriebe': [
                'elastische Bauteile beschädigt',
                'Korrosion',
                'schnelle Stufe i.O.',
                ],
            'Prüfbemerkungen|Triebstrang|Getriebeöl/Schmierung': [
                'Leckage',
                'Ölstand nicht i.O.',
                ],
            'Prüfbemerkungen|Triebstrang|Bremse': [
                'nicht prüfbar',
                'Belagstärke gering',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Triebstrang|Kupplung': [
                'ungenutzte Schmieranschlüsse',
                'nicht einsehbar',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Triebstrang|Drehdurchführung': [
                'Leckage',
                'nicht einsehbar',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Generator': [
                'lose Teile',
                'Anschlusskabel i.O.',
                ],
            'Prüfbemerkungen|Rotorsystem|Nabe': [
                'Beschichtungsschäden außen',
                'ansonsten i.O.',
                'nicht prüfbar',
                ],
            'Prüfbemerkungen|Rotorsystem|Verschraubungen': [
                'Wassereintritt',
                'Fettaustritt',
                'falscher Einbau',
                ],
            'Prüfbemerkungen|Rotorsystem|Pitchsystem': [
                'Antrieb ansonsten i.O.',
                'Zentralschmieranlage auffällig',
                ],
            'Prüfbemerkungen|Rotorsystem|Tiphydraulik': [
                'Leckage',
                'ansonsten i.O.',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Rotorsystem|Blitzableiteinrichtungen': [
                'Funkenstrecke lang',
                'ansonsten i.O.',
                'alles i.O.',
                ],
            'Prüfbemerkungen|Rotorsystem|Steuerschränke': [
                'Gehäuse auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Rotorsystem|Spinner': [
                'kein Spinner',
                'Befestigung auffällig',
                'ansonsten i.O.',
                ],
            'Prüfbemerkungen|Rotorsystem|Rotorblätter': [
                'Aluring auffällig',
                'ohne Seil i.O.',
                ],
            'Prüfbemerkungen|Rotorsystem|Sonstiges': [
                'Mängel Tiphydraulik',
                'Tiphydraulik ansonsten i.O.',
                ],
            'Prüfergebnis|Fazit': [
                'GESAMTEINDRUCK',
                'Menge Mängel',
                'Gesamteindruck',
                'Hauptmängel',
                'STANDSICHERHEIT',
                'Fazit Standsicherheit',
                'Detail Standsicherheit',
                'SICHERHEITSSYSTEME',
                'Fazit Sicherheitssysteme',
                'Detail Sicherheitssysteme',
                'BETRIEBSCHARAKTERISTIK',
                'Fazit Betriebscharakteristik',
                'Detail Betrieb',
                'kein Probelauf',
                'INSTANDHALTUNG',
                'Fazit Instandhaltung',
                'Detail Instandhaltung',
                'ARBEITSSICHERHEIT',
                'Fazit Arbeitssicherheit',
                'Detail Arbeitssicherheit',
                'ANTRIEBSSTRANG',
                'Fazit Antriebsstrang',
                'Detail Antriebsstrang',
                'SONSTIGES',
                'Detail Sonstiges',
                'WEITERER BETRIEB',
                'Fazit Weiterer Betrieb',
                'Detail Weiterer Betrieb',
                'Stilllegung',
                ],
            'Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Mängelbeseitigung': [
                'Intro vor Wiederinbetriebnahme',
                'vor Wiederinbetriebnahme erledigen',
                'Intro umgehend',
                'umgehend erledigen',
                'Intro kurzfristig',
                'kurzfristig erledigen',
                'Zeitpunkt Rest',
                'ungenannte Mängel letzte Prüfung wurden beseitigt',
                ],
            'Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Stellungnahmen/Nachweise': [
                'Stellungnahme Intro',
                'Risse Fundament',
                'Schweißnaht',
                'Temperatur',
                'Fettaustritt Hauptwelle/Hauptlager',
                'Fettaustritt Blattbolzen',
                ],
            'Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Pflichten des Auftraggebers bzw. des Betreibers': [
                'Verantwortung langjähriger Betrieb',
                'Nachweise einholen',
                'Zuweisung Verantwortlichkeiten',
                ],
            'Prüfergebnis|Auflagen bzw. weiteres Vorgehen|Termin für die wiederkehrende Prüfung': [
                'Prüfumfang WKP',
                'Termin WKP']}

def get_default_component_order():
    return ['Fundamenteinbauteil',
            'Fundamentadapter',
            'Einbauteil',
            'Turm',
            'Turm, Stahlblechteil',
            'Turm, Betonteil',
            'Betonteil',
            'Turm, Übergangsteil',
            'Übergangsstück',
            'Turm, Stahlrohrteil',
            'Turm, Stahlteil',
            'Stahlteil',
            'Bottom Sektion',
            'M1 Sektion',
            'M2 Sektion',
            'M3 Sektion',
            'M4 Sektion',
            'M5 Sektion',
            'M6 Sektion',
            'M7 Sektion',
            'Top Sektion',
            'Transformator',
            'Schaltanlage',
            'Umrichter',
            'Steuerung',
            'Aufstiegshilfe',
            'Maschinenträger',
            'Maschinenhaus',
            'Azimutlager',
            'Azimutbremsen',
            'Azimutbremse',
            'Azimutmotor',
            'Azimutmotoren',
            'Azimutgetriebe',
            'Hydraulik',
            'Getriebe',
            'Bremse',
            'Generator',
            'Generator (g)',
            'Generator (G)',
            'Rotor',
            'Stator',
            'Schleifringkörper',
            'Pitchlager',
            'Pitchmotor',
            'Pitchmotoren',
            'Pitchgetriebe',
            'Blattverlängerungen',
            'Rotorblätter']

def get_default_temperature_order():
    return ['Rotorlager',
            'Getriebeölsumpf',
            'Getriebeöleingang',
            'Getriebelager 1',
            'Getriebelager 2',
            'Statorwicklung',
            'Generatorlager 1',
            'Generatorlager 2',
            'Schleifring',
            'Pitchmotor 1',
            'Pitchmotor 2',
            'Pitchmotor 3',
            'Trafo Eisenkern',
            'Trafo L2 (660V)',
            'Trafo L2 (950V)',
            'Trafo Innenraum',
            'Trafo Innenr.',
            'Eig.bed.trafo',
            'Hydr',
            'Getr',
            'Trafo',
            'Lag.1',
            '6: GearHSBearA',
            'Gen Lag.1',
            '8: Gen.Ph 1',
            '9: Gen.Ph 2',
            '10: Gen.Ph 3',
            '16: TrafoWind L1',
            '17: TrafoWind L2',
            '18: TrafoWind L3',
            '25: GenBear DE',
            '26: GenBear NDE',
            '27: GearOilIn',
            '28: GearHSBearB',
            '29: GearHSBearC',
            '31: MainRotorEnd',
            '33: AuxTrafo',
            '35: TrafoCore L1',
            '36: TrafoCore L2',
            '37: TrafoCore L3',
            '38: GearIBearA',
            '39: GearIBearB',
            '50: ConvGenWater',
            '51: HydGearWater',
            '52: MainTankOil',
            '98: Nacell Temp1',
            '99: Nacell Temp2',
            'Hauptlager 1(Rot)',
            'GETR LagTemp 1(Gen)',
            'GETR LagTemp 2(Rot)',
            'Getriebeöl',
            'Lager AS',
            'Lager BS',
            'L1',
            'L2',
            'L3']


def get_default_inspections_dict():
    return {
            'index': [('07/2024', 'WKP', 'Nortank', '12-345')],
            'columns': ['inspectors', 'testrun_wind', 'testrun_power', 'wea_output', 'wea_hours', 'scope'],
            'data': [[
                "[('Prüfung', 'Axel Jensen, 8.2', '06.08.2024', '1-6\\\\,m/s, 25°C'), ('Prüfung', 'Tade Jensen, 8.2', '', '')]",
                '', '', 7000000, 90000, 'Prüfung der gesamten Anlage ohne Rotorblätter'
            ]],
            'index_names': ['insp_year', 'insp_type', 'oem', 'turbine_id'],
            'column_names': [None]
            }

def get_default_turbines_dict():
    return {
            'index': [('Nortank', '12-345')],
            'columns': [
                'model', 'submodel', 'windfarm', 'location', 'farm_number',
                'rated_power', 'hub_height', 'rotor_diam', 'tower_type',
                'startup_date', 'coordinates', 'owner', 'operator', 'note'
            ],
            'data': [[
                'NTK 500', '- 41', 'Flensburg', 'D - 24941 Flensburg', '1', 500.0,
                50.0, 41.0, 'Stahlrohr', '19.10.1995', '(54.772707, 9.375145)',
                'Wind ist schön GmbH & Co.KG|Am Ausblick 123|25813 Husum',
                'Betreiberino mbH', 'Akkuschrauber mitnehmen'
            ]],
            'index_names': ['oem', 'sn'],
            'column_names': [None]
            }

def get_default_temperatures_dict():
    return {
            'index': [('Senvion', '3.2M114', 'Generatorlager 1', 'SEN301392', 2023)],
            'columns': ['value'],
            'data': [[38.8]],
            'index_names': ['oem', 'model', 'name', 'turbine_id', 'insp_year'],
            'column_names': [None]
            }

def get_default_components_dict():
    return {
            'index': [('Enercon', 'E82', 'Schaltanlage', 'E2')],
            'columns': ['component_oem', 'component_model', 'sn'],
            'data': [['Ormazabal', 'GA2K1LSF', '1150S138']],
            'index_names': ['oem', 'model', 'component', 'turbine_id'],
            'column_names': [None]
            }

def get_default_remarks_dict(time):
    return {
            'index': [('Nortank',
            '95-575',
            '20aa',
            'WKP',
            'DF HEILUNG',
            time)],
            'columns': ['fulltext', 'flag', 'image_names', 'author', 'position'],
            'data': [['Die Zufahrt zur WEA war zum Zeitpunkt der Prüfung gut befahrbar.',
            'V',
            '[]',
            'Tade Jensen',
            '']],
            'index_names': ['oem',
            'turbine_id',
            'insp_year',
            'inspection_type',
            'address',
            'create_time'],
            'column_names': [None]
            }

